### ISSUE TITLE
talos_version should be a version number instead of a version tag

### ISSUE THREAD

**Issue by rgl** [siderolabs/terraform-provider-talos#119] opened 2023-09-30 18:06 UTC
its somewhat confusing what we should put in the `talos_version` and `kubernetes_version` properties. they both should use the same convention or normalize the provided version to the same format. FWIW, I prefer to use a proper version number (without `v` letter prefix).

**Comment by smira** [comment] 2024-03-06 16:00
Duplicate of #81

**Closed by smira** 2024-03-06 16:00 UTC
